[run]
init_cmds = [
	["go", "install"],
	["go", "build"],
	["./smoljanin.ru","web"]
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = [
    "$WORKDIR/conf",
    "$WORKDIR/models",
    "$WORKDIR/modules",
    "$WORKDIR/controllers",
    "$WORKDIR/cmd"
]						# Directories to watch
watch_exts = [".go",".conf"]				# Extensions to watch
ignore = [".git", "node_modules"] 	# Directories to exclude from watching
ignore_files = []					# Regexps for ignoring specific notifies
build_delay = 1500					# Minimal interval to Trigger build event
interrupt_timout = 15				# Time to wait until force kill
cmds = [
	["go", "install"],
	["go", "build"],
	["./smoljanin.ru", "web"]
]									# Commands to run

[sync]
listen_addr = ":5050"
remote_addr = ":5050"